services:
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        ANNOUNCED_IP: ${ANNOUNCED_IP}
        MAX_PORT: ${MAX_PORT}
        MIN_PORT: ${MIN_PORT}
    environment:
      - ANNOUNCED_IP=${ANNOUNCED_IP}
      - MAX_PORT=${MAX_PORT}
      - MIN_PORT=${MIN_PORT}
    ports:
      - '5000:5000'
      - '10000-10100:10000-10100'
    expose:
      - 5000

  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
        NEXTAUTH_URL: ${NEXTAUTH_URL}
        LOGIN_USERNAME: ${LOGIN_USERNAME}
        LOGIN_PASSWORD: ${LOGIN_PASSWORD}
        NEXT_PUBLIC_WS_URL: ${NEXT_PUBLIC_WS_URL}
    ports:
      - '3000:3000'
    environment:
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - LOGIN_USERNAME=${LOGIN_USERNAME}
      - LOGIN_PASSWORD=${LOGIN_PASSWORD}
      - NEXT_PUBLIC_WS_URL=${NEXT_PUBLIC_WS_URL}
    depends_on:
      - server
    expose:
      - 3000
