services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ANNOUNCED_IP: ${ANNOUNCED_IP}
        MAX_PORT: ${MAX_PORT}
        MIN_PORT: ${MIN_PORT}
    environment:
      - ANNOUNCED_IP=${ANNOUNCED_IP}
      - MAX_PORT=${MAX_PORT}
      - MIN_PORT=${MIN_PORT}
    ports:
      - '5000:5000'
      - '10000-10100:10000-10100'
    expose:
      - 5000
      - 10000-10100
